// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtU60yUN5sSRd79dE0Zy-mptCLhpFq-oE',
    appId: '1:127306246040:web:9090695103a698ca44aded',
    messagingSenderId: '127306246040',
    projectId: 'coffeeshop-0101',
    authDomain: 'coffeeshop-0101.firebaseapp.com',
    storageBucket: 'coffeeshop-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWWT8bE0R5H_QxOtuxrJ-pfCuXt9deTWM',
    appId: '1:127306246040:android:131b5de87be439ec44aded',
    messagingSenderId: '127306246040',
    projectId: 'coffeeshop-0101',
    storageBucket: 'coffeeshop-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhKUA6ReXUOesZkgOAjo3aWrUUjehRv4E',
    appId: '1:127306246040:ios:b00182bad83dd5c844aded',
    messagingSenderId: '127306246040',
    projectId: 'coffeeshop-0101',
    storageBucket: 'coffeeshop-0101.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhKUA6ReXUOesZkgOAjo3aWrUUjehRv4E',
    appId: '1:127306246040:ios:b00182bad83dd5c844aded',
    messagingSenderId: '127306246040',
    projectId: 'coffeeshop-0101',
    storageBucket: 'coffeeshop-0101.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtU60yUN5sSRd79dE0Zy-mptCLhpFq-oE',
    appId: '1:127306246040:web:4c928035e3211a4044aded',
    messagingSenderId: '127306246040',
    projectId: 'coffeeshop-0101',
    authDomain: 'coffeeshop-0101.firebaseapp.com',
    storageBucket: 'coffeeshop-0101.appspot.com',
  );
}
